---
- name: Install webupd8team repo
  apt_repository: 
        repo='ppa:webupd8team/java'
        state=present

- name: Accept the Java License
  debconf:
        name='oracle-java8-installer'
        question='shared/accepted-oracle-license-v1-1'
        vtype='select'
        value='true'

- name: Update Cache and install java8
  apt: 
        update_cache=yes
        name=oracle-java8-installer
        state=present
